/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PROZE.GUI;

/**
 *
 * @author Maciek
 */
public class CreateGroup extends javax.swing.JPanel {

    /**
     * Creates new form CreateGroup
     */
    public CreateGroup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JSeparator();

        setMinimumSize(new java.awt.Dimension(610, 321));
        setPreferredSize(new java.awt.Dimension(610, 321));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel9.setBackground(new java.awt.Color(0, 204, 51));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel10.setBackground(new java.awt.Color(0, 204, 51));
        jPanel10.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("Podaj nazwę");
        jPanel10.add(jLabel4);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel10.add(jTextField4);

        jPanel9.add(jPanel10);

        jSeparator7.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator7.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator7.setMaximumSize(new java.awt.Dimension(50, 5));
        jSeparator7.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator7.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel9.add(jSeparator7);

        jLabel5.setText("Dodaj opis");
        jPanel9.add(jLabel5);

        jPanel11.setBackground(new java.awt.Color(0, 204, 51));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.X_AXIS));

        jSeparator8.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator8.setMaximumSize(new java.awt.Dimension(5, 50));
        jSeparator8.setMinimumSize(new java.awt.Dimension(5, 50));
        jSeparator8.setPreferredSize(new java.awt.Dimension(5, 50));
        jPanel11.add(jSeparator8);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel11.add(jScrollPane2);

        jSeparator9.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator9.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator9.setMaximumSize(new java.awt.Dimension(5, 50));
        jSeparator9.setMinimumSize(new java.awt.Dimension(5, 50));
        jSeparator9.setPreferredSize(new java.awt.Dimension(5, 50));
        jPanel11.add(jSeparator9);

        jPanel9.add(jPanel11);

        jSeparator10.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator10.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator10.setMaximumSize(new java.awt.Dimension(50, 5));
        jSeparator10.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator10.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel9.add(jSeparator10);

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));
        jPanel9.add(jPanel12);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        jButton2.setText("Ok");
        jButton2.setMaximumSize(new java.awt.Dimension(63, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(63, 23));
        jPanel13.add(jButton2);

        jButton4.setText("Anuluj");
        jPanel13.add(jButton4);

        jPanel9.add(jPanel13);

        jSeparator11.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator11.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator11.setMaximumSize(new java.awt.Dimension(50, 5));
        jSeparator11.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator11.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel9.add(jSeparator11);

        add(jPanel9);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
