/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PROZE.GUI;

/**
 *
 * @author Maciek
 */
public class Create extends javax.swing.JPanel {

    /**
     * Creates new form Menage
     */
    public Create() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel14 = new javax.swing.JPanel();
        jSeparator17 = new javax.swing.JSeparator();
        jPanel18 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jSeparator14 = new javax.swing.JSeparator();
        jPanel19 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jPanel20 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jPanel21 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jPanel22 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jPanel23 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jButton7 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel17 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(0, 204, 51));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jTabbedPane1.setBackground(new java.awt.Color(0, 204, 51));
        jTabbedPane1.setDoubleBuffered(true);

        jPanel3.setBackground(new java.awt.Color(0, 204, 51));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Podaj nazwę");
        jPanel1.add(jLabel2);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);

        jPanel3.add(jPanel1);

        jSeparator1.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator1.setMaximumSize(new java.awt.Dimension(50, 5));
        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel3.add(jSeparator1);

        jPanel5.setBackground(new java.awt.Color(0, 204, 51));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        jPanel6.setBackground(new java.awt.Color(0, 204, 51));
        jPanel6.setMinimumSize(new java.awt.Dimension(200, 120));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        jLabel3.setText("Wybierz grupę");
        jPanel6.add(jLabel3);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setMaximumSize(new java.awt.Dimension(80, 40));
        jList1.setMinimumSize(new java.awt.Dimension(100, 40));
        jList1.setName(""); // NOI18N
        jList1.setPreferredSize(new java.awt.Dimension(100, 40));
        jScrollPane3.setViewportView(jList1);

        jPanel6.add(jScrollPane3);

        jButton6.setText("Potwierdź");
        jPanel6.add(jButton6);

        jLabel6.setText("Wybierz kategorię");
        jPanel6.add(jLabel6);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.setMaximumSize(new java.awt.Dimension(100, 40));
        jList2.setMinimumSize(new java.awt.Dimension(100, 40));
        jList2.setPreferredSize(new java.awt.Dimension(100, 40));
        jScrollPane4.setViewportView(jList2);

        jPanel6.add(jScrollPane4);

        jButton5.setText("Potwierdź");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5);

        jPanel5.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(0, 204, 51));
        jPanel7.setMinimumSize(new java.awt.Dimension(400, 67));
        jPanel7.setPreferredSize(new java.awt.Dimension(400, 265));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane3.setBackground(new java.awt.Color(0, 204, 51));
        jTabbedPane3.setDoubleBuffered(true);
        jTabbedPane3.setMinimumSize(new java.awt.Dimension(400, 141));

        jPanel14.setBackground(new java.awt.Color(0, 204, 51));
        jPanel14.setForeground(new java.awt.Color(0, 204, 51));
        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.PAGE_AXIS));

        jSeparator17.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator17.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator17.setMaximumSize(new java.awt.Dimension(32767, 5));
        jSeparator17.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator17.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel14.add(jSeparator17);

        jPanel18.setBackground(new java.awt.Color(0, 204, 51));
        jPanel18.setForeground(new java.awt.Color(0, 204, 51));
        jPanel18.setLayout(new javax.swing.BoxLayout(jPanel18, javax.swing.BoxLayout.X_AXIS));

        jLabel11.setText("Pytanie");
        jPanel18.add(jLabel11);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane7.setViewportView(jTextArea5);

        jPanel18.add(jScrollPane7);

        jPanel14.add(jPanel18);

        jSeparator14.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator14.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator14.setMaximumSize(new java.awt.Dimension(32767, 5));
        jSeparator14.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator14.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel14.add(jSeparator14);

        jPanel19.setBackground(new java.awt.Color(0, 204, 51));
        jPanel19.setForeground(new java.awt.Color(0, 204, 51));
        jPanel19.setLayout(new javax.swing.BoxLayout(jPanel19, javax.swing.BoxLayout.X_AXIS));

        jLabel7.setText("Odpowiedź A ");
        jPanel19.add(jLabel7);

        jTextField3.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jPanel19.add(jTextField3);

        jPanel14.add(jPanel19);

        jSeparator13.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator13.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator13.setMaximumSize(new java.awt.Dimension(32767, 5));
        jSeparator13.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator13.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel14.add(jSeparator13);

        jPanel20.setBackground(new java.awt.Color(0, 204, 51));
        jPanel20.setForeground(new java.awt.Color(0, 204, 51));
        jPanel20.setLayout(new javax.swing.BoxLayout(jPanel20, javax.swing.BoxLayout.LINE_AXIS));

        jLabel8.setText("Odpowiedź B ");
        jPanel20.add(jLabel8);

        jTextField5.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel20.add(jTextField5);

        jPanel14.add(jPanel20);

        jSeparator12.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator12.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator12.setMaximumSize(new java.awt.Dimension(32767, 5));
        jSeparator12.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator12.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel14.add(jSeparator12);

        jPanel21.setBackground(new java.awt.Color(0, 204, 51));
        jPanel21.setForeground(new java.awt.Color(0, 204, 51));
        jPanel21.setLayout(new javax.swing.BoxLayout(jPanel21, javax.swing.BoxLayout.LINE_AXIS));

        jLabel12.setText("Odpowiedź C ");
        jPanel21.add(jLabel12);

        jTextField6.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jPanel21.add(jTextField6);

        jPanel14.add(jPanel21);

        jSeparator15.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator15.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator15.setMaximumSize(new java.awt.Dimension(32767, 5));
        jSeparator15.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator15.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel14.add(jSeparator15);

        jPanel22.setBackground(new java.awt.Color(0, 204, 51));
        jPanel22.setForeground(new java.awt.Color(0, 204, 51));
        jPanel22.setLayout(new javax.swing.BoxLayout(jPanel22, javax.swing.BoxLayout.LINE_AXIS));

        jLabel13.setText("Odpowiedź D ");
        jPanel22.add(jLabel13);

        jTextField1.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jPanel22.add(jTextField1);

        jPanel14.add(jPanel22);

        jSeparator16.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator16.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator16.setMaximumSize(new java.awt.Dimension(32767, 5));
        jSeparator16.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator16.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel14.add(jSeparator16);

        jPanel23.setBackground(new java.awt.Color(0, 204, 51));
        jPanel23.setForeground(new java.awt.Color(0, 204, 51));
        jPanel23.setLayout(new javax.swing.BoxLayout(jPanel23, javax.swing.BoxLayout.X_AXIS));

        jLabel14.setText("Prawidłowa odpowiedź");
        jPanel23.add(jLabel14);

        jToggleButton1.setText("A");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel23.add(jToggleButton1);

        jToggleButton2.setText("B");
        jPanel23.add(jToggleButton2);

        jToggleButton3.setText("C");
        jPanel23.add(jToggleButton3);

        jToggleButton4.setText("D");
        jPanel23.add(jToggleButton4);

        jButton7.setText("Dodaj pytanie");
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel23.add(jButton7);

        jPanel14.add(jPanel23);

        jTabbedPane3.addTab("Dodaj pytanie zamknięte", jPanel14);

        jPanel15.setBackground(new java.awt.Color(0, 204, 51));
        jPanel15.setForeground(new java.awt.Color(0, 204, 51));
        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.Y_AXIS));

        jPanel16.setBackground(new java.awt.Color(0, 204, 51));
        jPanel16.setForeground(new java.awt.Color(0, 204, 51));
        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.Y_AXIS));

        jLabel9.setText("Pytanie");
        jPanel16.add(jLabel9);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane5.setViewportView(jTextArea3);

        jPanel16.add(jScrollPane5);

        jPanel15.add(jPanel16);

        jPanel17.setBackground(new java.awt.Color(0, 204, 51));
        jPanel17.setForeground(new java.awt.Color(0, 204, 51));
        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.Y_AXIS));

        jLabel10.setText("             Odpowiedź");
        jPanel17.add(jLabel10);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane6.setViewportView(jTextArea4);

        jPanel17.add(jScrollPane6);

        jPanel15.add(jPanel17);

        jButton8.setText("Dodaj pytanie");
        jPanel15.add(jButton8);

        jTabbedPane3.addTab("Dodaj pytanie otwarte", jPanel15);

        jPanel7.add(jTabbedPane3);

        jPanel5.add(jPanel7);

        jPanel3.add(jPanel5);

        jLabel1.setText("Dodaj opis");
        jPanel3.add(jLabel1);

        jPanel2.setBackground(new java.awt.Color(0, 204, 51));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jSeparator4.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator4.setMaximumSize(new java.awt.Dimension(5, 50));
        jSeparator4.setMinimumSize(new java.awt.Dimension(5, 50));
        jSeparator4.setPreferredSize(new java.awt.Dimension(5, 50));
        jPanel2.add(jSeparator4);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);

        jSeparator6.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator6.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator6.setMaximumSize(new java.awt.Dimension(5, 50));
        jSeparator6.setMinimumSize(new java.awt.Dimension(5, 50));
        jSeparator6.setPreferredSize(new java.awt.Dimension(5, 50));
        jPanel2.add(jSeparator6);

        jPanel3.add(jPanel2);

        jSeparator2.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator2.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator2.setMaximumSize(new java.awt.Dimension(50, 5));
        jSeparator2.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel3.add(jSeparator2);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));
        jPanel3.add(jPanel8);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setText("Ok");
        jButton1.setMaximumSize(new java.awt.Dimension(63, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(63, 23));
        jPanel4.add(jButton1);

        jButton3.setText("Anuluj");
        jPanel4.add(jButton3);

        jPanel3.add(jPanel4);

        jSeparator3.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator3.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator3.setMaximumSize(new java.awt.Dimension(50, 5));
        jSeparator3.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator3.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel3.add(jSeparator3);

        jTabbedPane1.addTab("Utwórz test", jPanel3);

        jPanel9.setBackground(new java.awt.Color(0, 204, 51));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel10.setBackground(new java.awt.Color(0, 204, 51));
        jPanel10.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("Podaj nazwę");
        jPanel10.add(jLabel4);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel10.add(jTextField4);

        jPanel9.add(jPanel10);

        jSeparator7.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator7.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator7.setMaximumSize(new java.awt.Dimension(50, 5));
        jSeparator7.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator7.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel9.add(jSeparator7);

        jLabel5.setText("Dodaj opis");
        jPanel9.add(jLabel5);

        jPanel11.setBackground(new java.awt.Color(0, 204, 51));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.X_AXIS));

        jSeparator8.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator8.setMaximumSize(new java.awt.Dimension(5, 50));
        jSeparator8.setMinimumSize(new java.awt.Dimension(5, 50));
        jSeparator8.setPreferredSize(new java.awt.Dimension(5, 50));
        jPanel11.add(jSeparator8);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel11.add(jScrollPane2);

        jSeparator9.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator9.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator9.setMaximumSize(new java.awt.Dimension(5, 50));
        jSeparator9.setMinimumSize(new java.awt.Dimension(5, 50));
        jSeparator9.setPreferredSize(new java.awt.Dimension(5, 50));
        jPanel11.add(jSeparator9);

        jPanel9.add(jPanel11);

        jSeparator10.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator10.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator10.setMaximumSize(new java.awt.Dimension(50, 5));
        jSeparator10.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator10.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel9.add(jSeparator10);

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));
        jPanel9.add(jPanel12);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        jButton2.setText("Ok");
        jButton2.setMaximumSize(new java.awt.Dimension(63, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(63, 23));
        jPanel13.add(jButton2);

        jButton4.setText("Anuluj");
        jPanel13.add(jButton4);

        jPanel9.add(jPanel13);

        jSeparator11.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator11.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator11.setMaximumSize(new java.awt.Dimension(50, 5));
        jSeparator11.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator11.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel9.add(jSeparator11);

        jTabbedPane1.addTab("Utwórz grupę", jPanel9);
        jPanel9.getAccessibleContext().setAccessibleName("Utwórz grupę");

        add(jTabbedPane1);
        jTabbedPane1.getAccessibleContext().setAccessibleName("Urtwórz grupę");

        getAccessibleContext().setAccessibleName("Utwórz test");
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    // End of variables declaration//GEN-END:variables
}
