/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PROZE.GUI;

import PROZE.GUI.EventListeners.NavigationListener;
import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author Krzysztof
 */
public class LeftPanel extends javax.swing.JPanel {

    private final Set<NavigationListener> navigationListeners = new HashSet<>();

    /**
     * Creates new form LeftPanel
     */
    public LeftPanel() {
        initComponents();
    }

    public void addNavigationListener(NavigationListener listener) {
        this.navigationListeners.add(listener);
    }

    public void removeNavitaionListener(NavigationListener listener) {
        this.navigationListeners.remove(listener);
    }

    public void setDisplayedUserName(String displayedUserName) {
        this.userNameLabel.setText(displayedUserName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameLabel = new javax.swing.JLabel();
        viewProfileButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        myGroupsButton = new javax.swing.JButton();
        myTestsButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        notificationsButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        newGroupButton = new javax.swing.JButton();

        userNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userNameLabel.setText("<Nazwa użytkownika>");

        viewProfileButton.setText("Mój profil");
        viewProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Wyloguj");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        myGroupsButton.setText("Moje grupy");
        myGroupsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myGroupsButtonActionPerformed(evt);
            }
        });

        myTestsButton.setText("Moje testy");
        myTestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myTestsButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Wyszukaj...");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        notificationsButton.setText("Brak powiadomień");
        notificationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationsButtonActionPerformed(evt);
            }
        });

        newGroupButton.setText("Nowa grupa");
        newGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGroupButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newGroupButton)
                            .addComponent(userNameLabel)
                            .addComponent(viewProfileButton)
                            .addComponent(logoutButton)
                            .addComponent(myGroupsButton)
                            .addComponent(myTestsButton)
                            .addComponent(searchButton)
                            .addComponent(notificationsButton))
                        .addGap(0, 109, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewProfileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myGroupsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myTestsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newGroupButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(notificationsButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileButtonActionPerformed
        for (NavigationListener listener : navigationListeners) {
            listener.navigatedToViewProfile();
        }
    }//GEN-LAST:event_viewProfileButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        for (NavigationListener listener : navigationListeners) {
            listener.navigatedToLogout();
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void myGroupsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myGroupsButtonActionPerformed
        for (NavigationListener listener : navigationListeners) {
            listener.navigatedToMyGroups();
        }
    }//GEN-LAST:event_myGroupsButtonActionPerformed

    private void myTestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myTestsButtonActionPerformed
        for (NavigationListener listener : navigationListeners) {
            listener.navigatedToMyTests();
        }
    }//GEN-LAST:event_myTestsButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        for (NavigationListener listener : navigationListeners) {
            listener.navigatedToSearch();
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void notificationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationsButtonActionPerformed
        for (NavigationListener listener : navigationListeners) {
            listener.navigatedToNotifications();
        }
    }//GEN-LAST:event_notificationsButtonActionPerformed

    private void newGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGroupButtonActionPerformed
        for (NavigationListener listener : navigationListeners) {
            listener.navigatedToGroupManager(null, true);
        }
    }//GEN-LAST:event_newGroupButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton myGroupsButton;
    private javax.swing.JButton myTestsButton;
    private javax.swing.JButton newGroupButton;
    private javax.swing.JButton notificationsButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JButton viewProfileButton;
    // End of variables declaration//GEN-END:variables
}
