/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PROZE.GUI;

import EntitiesModels.UserEntity;
import PROZE.GUI.EventListeners.MyAccountListener;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author Maciek
 */
public class MyAccountPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainWindow
     */
    private final UserEntity currentUser;
    private final Set<MyAccountListener> myAccountListeners = new HashSet<>();
    public MyAccountPanel(UserEntity User) {
        currentUser = User;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        warningMessage = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        buttonWarning = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        firstNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        secondNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        loginTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        emailTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        firstPasswordField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        secondPasswordField = new javax.swing.JPasswordField();
        jPanel8 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Pole \"Hasło\" i \"Powtórz hasło\" \nsą  różne uzupełnij je \njeszcze raz");
        jScrollPane2.setViewportView(jTextArea2);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Uwaga");

        buttonWarning.setText("Ok");
        buttonWarning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWarningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonWarning)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonWarning)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        warningMessage.getContentPane().add(jPanel9, java.awt.BorderLayout.CENTER);

        setBackground(new java.awt.Color(0, 204, 51));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        setLayout(new java.awt.GridLayout(0, 2, 15, 15));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Imię:");
        add(jLabel7);

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        firstNameTextField.setMaximumSize(new java.awt.Dimension(259, 25));
        firstNameTextField.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel1.add(firstNameTextField);

        add(jPanel1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nazwisko:");
        add(jLabel1);

        jPanel2.setBackground(new java.awt.Color(0, 204, 51));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        secondNameTextField.setMaximumSize(new java.awt.Dimension(259, 25));
        secondNameTextField.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel2.add(secondNameTextField);

        add(jPanel2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Login:");
        add(jLabel2);

        jPanel3.setBackground(new java.awt.Color(0, 204, 51));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        loginTextField.setMaximumSize(new java.awt.Dimension(259, 25));
        loginTextField.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel3.add(loginTextField);

        add(jPanel3);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Adres E-mail:");
        add(jLabel3);

        jPanel4.setBackground(new java.awt.Color(0, 204, 51));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        emailTextField.setMaximumSize(new java.awt.Dimension(259, 25));
        emailTextField.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel4.add(emailTextField);

        add(jPanel4);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Hasło:");
        add(jLabel4);

        jPanel5.setBackground(new java.awt.Color(0, 204, 51));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        firstPasswordField.setMaximumSize(new java.awt.Dimension(259, 25));
        firstPasswordField.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel5.add(firstPasswordField);

        add(jPanel5);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Powtórz hasło:");
        add(jLabel5);

        jPanel6.setBackground(new java.awt.Color(0, 204, 51));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        secondPasswordField.setMaximumSize(new java.awt.Dimension(259, 25));
        secondPasswordField.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel6.add(secondPasswordField);

        add(jPanel6);

        jPanel8.setBackground(new java.awt.Color(0, 204, 51));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        cancelButton.setText("Anuluj");
        cancelButton.setMaximumSize(new java.awt.Dimension(259, 25));
        cancelButton.setMinimumSize(new java.awt.Dimension(6, 20));
        cancelButton.setPreferredSize(new java.awt.Dimension(150, 25));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel8.add(cancelButton);

        add(jPanel8);

        jPanel7.setBackground(new java.awt.Color(0, 204, 51));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        editButton.setText("Zmień");
        editButton.setMaximumSize(new java.awt.Dimension(259, 25));
        editButton.setMinimumSize(new java.awt.Dimension(6, 20));
        editButton.setPreferredSize(new java.awt.Dimension(150, 25));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel7.add(editButton);

        add(jPanel7);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.firstNameTextField.setText(null);
        this.secondNameTextField.setText(null);
        this.loginTextField.setText(null);
        this.emailTextField.setText(null);
        this.secondPasswordField.setText(null);
        this.firstPasswordField.setText(null);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        String name = firstNameTextField.getText();
        String secondName = secondNameTextField.getText();
        String login = loginTextField.getText();
        String email = emailTextField.getText();
        char[] secondPassword = secondPasswordField.getPassword();
        char[] firstPassword = firstPasswordField.getPassword();
        if (Arrays.equals(firstPassword, secondPassword)) {
            for (MyAccountListener listener : this.myAccountListeners) {
                listener.changesConfirmed(name, secondName, login, email, firstPassword);
            }
        }
        else{
            this.warningMessage.setVisible(true);
        }
   
    }//GEN-LAST:event_editButtonActionPerformed

    private void buttonWarningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWarningActionPerformed
        this.firstPasswordField.setText(null);
        this.secondPasswordField.setText(null);
        this.warningMessage.setVisible(false);
    }//GEN-LAST:event_buttonWarningActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buttonWarning;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JPasswordField firstPasswordField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JTextField secondNameTextField;
    private javax.swing.JPasswordField secondPasswordField;
    private javax.swing.JDialog warningMessage;
    // End of variables declaration//GEN-END:variables
}
