/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PROZE.GUI;

import EntitiesModels.GroupEntity;
import EntitiesModels.TestDescription;
import java.awt.Color;
import java.awt.Component;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Formatter;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Maciek
 */
public class SearchPanel extends javax.swing.JPanel {

    private final DefaultListModel<GroupEntity> groupListModel = new DefaultListModel<GroupEntity>();
    private final DefaultListModel<TestDescription> testListModel = new DefaultListModel<TestDescription>();

    /**
     * Creates new form Search
     */
    public SearchPanel() {
        initComponents();
        addGroupPopupMenu();
        addTestPopupMenu();
    }

    private void addGroupPopupMenu() {
        JPopupMenu popupMenu1 = new JPopupMenu() {

            @Override
            public void show(Component invoker, int x, int y) {
                int selectedIndex = groupList.getSelectedIndex();
                if (selectedIndex == groupList.locationToIndex(new Point(x, y))) {
                    super.show(invoker, x, y);
                }
            }

        };

        JMenuItem openGroup = new JMenuItem("Przeglądaj grupę");
        openGroup.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        popupMenu1.add(openGroup);
        JMenuItem joinGroup = new JMenuItem("Dołacz do grupy");
        joinGroup.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        popupMenu1.add(joinGroup);
        this.groupList.setComponentPopupMenu(popupMenu1);

    }

    private void addTestPopupMenu() {
        JPopupMenu popupMenu2 = new JPopupMenu() {

            @Override
            public void show(Component invoker, int x, int y) {
                int selectedIndex = testsList.getSelectedIndex();
                if (selectedIndex == testsList.locationToIndex(new Point(x, y))) {
                    super.show(invoker, x, y);
                }
            }

        };

        JMenuItem openTest = new JMenuItem("Rozwiąż test");
        openTest.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        popupMenu2.add(openTest);
        JMenuItem saveTest = new JMenuItem("Ściągnij test");
        saveTest.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        popupMenu2.add(saveTest);
//        if(editPermitted() == true){
//            JMenuItem editTest = new JMenuItem("Edytuj test");
//            editTest.addActionListener(new ActionListener() {
//
//                @Override
//                public void actionPerformed(ActionEvent e) {
//                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//                }
//            });
//            popupMenu2.add(editTest);
//        }
        this.testsList.setComponentPopupMenu(popupMenu2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator18 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator26 = new javax.swing.JSeparator();
        jPanel13 = new javax.swing.JPanel();
        jSeparator21 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        jTextField3 = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        jComboBox6 = new javax.swing.JComboBox();
        jSeparator24 = new javax.swing.JSeparator();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        groupList = new javax.swing.JList();
        jPanel12 = new javax.swing.JPanel();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        testsList = new javax.swing.JList();
        jPanel10 = new javax.swing.JPanel();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(0, 204, 51));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setBackground(new java.awt.Color(0, 204, 51));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jSeparator26.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator26.setMaximumSize(new java.awt.Dimension(32767, 5));
        jPanel1.add(jSeparator26);

        jPanel13.setBackground(new java.awt.Color(0, 204, 51));
        jPanel13.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.X_AXIS));

        jSeparator21.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator21.setMaximumSize(new java.awt.Dimension(5, 32767));
        jSeparator21.setMinimumSize(new java.awt.Dimension(5, 10));
        jSeparator21.setPreferredSize(new java.awt.Dimension(5, 10));
        jPanel13.add(jSeparator21);

        jLabel6.setText("Wyszukaj");
        jPanel13.add(jLabel6);

        jSeparator22.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator22.setMaximumSize(new java.awt.Dimension(5, 32767));
        jSeparator22.setMinimumSize(new java.awt.Dimension(5, 10));
        jSeparator22.setPreferredSize(new java.awt.Dimension(5, 10));
        jPanel13.add(jSeparator22);

        jTextField3.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel13.add(jTextField3);

        jSeparator23.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator23.setMaximumSize(new java.awt.Dimension(5, 32767));
        jSeparator23.setMinimumSize(new java.awt.Dimension(5, 10));
        jSeparator23.setPreferredSize(new java.awt.Dimension(5, 10));
        jPanel13.add(jSeparator23);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nazwa", "Autor", "Data utworzenia" }));
        jComboBox6.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel13.add(jComboBox6);

        jSeparator24.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator24.setMaximumSize(new java.awt.Dimension(5, 32767));
        jSeparator24.setMinimumSize(new java.awt.Dimension(5, 10));
        jSeparator24.setPreferredSize(new java.awt.Dimension(5, 10));
        jPanel13.add(jSeparator24);

        jPanel1.add(jPanel13);

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));

        groupList.setModel(this.testListModel);
        jScrollPane3.setViewportView(groupList);

        jPanel11.add(jScrollPane3);

        jPanel12.setBackground(new java.awt.Color(0, 204, 51));
        jPanel12.setForeground(new java.awt.Color(0, 204, 51));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator19.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator19.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator19.setMaximumSize(new java.awt.Dimension(10, 5));
        jSeparator19.setMinimumSize(new java.awt.Dimension(10, 5));
        jSeparator19.setPreferredSize(new java.awt.Dimension(10, 5));
        jPanel12.add(jSeparator19);

        jLabel5.setText("Sortuj");
        jPanel12.add(jLabel5);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alfabetycznie rosnąco", "Alfabetycznie malejąco" }));
        jComboBox5.setMaximumSize(new java.awt.Dimension(32767, 20));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel12.add(jComboBox5);

        jSeparator20.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator20.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator20.setMaximumSize(new java.awt.Dimension(32767, 5));
        jSeparator20.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator20.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel12.add(jSeparator20);

        jPanel11.add(jPanel12);

        jPanel1.add(jPanel11);

        jSeparator25.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator25.setMaximumSize(new java.awt.Dimension(32767, 5));
        jPanel1.add(jSeparator25);

        jTabbedPane1.addTab("Wyszukaj grupę", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 204, 51));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jSeparator5.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator5.setMaximumSize(new java.awt.Dimension(32767, 5));
        jPanel2.add(jSeparator5);

        jPanel5.setBackground(new java.awt.Color(0, 204, 51));
        jPanel5.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        jSeparator2.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator2.setMaximumSize(new java.awt.Dimension(5, 32767));
        jSeparator2.setMinimumSize(new java.awt.Dimension(5, 10));
        jSeparator2.setPreferredSize(new java.awt.Dimension(5, 10));
        jPanel5.add(jSeparator2);

        jLabel1.setText("Wyszukaj");
        jPanel5.add(jLabel1);

        jSeparator4.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator4.setMaximumSize(new java.awt.Dimension(5, 32767));
        jSeparator4.setMinimumSize(new java.awt.Dimension(5, 10));
        jSeparator4.setPreferredSize(new java.awt.Dimension(5, 10));
        jPanel5.add(jSeparator4);

        jTextField1.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField1);

        jSeparator3.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator3.setMaximumSize(new java.awt.Dimension(5, 32767));
        jSeparator3.setMinimumSize(new java.awt.Dimension(5, 10));
        jSeparator3.setPreferredSize(new java.awt.Dimension(5, 10));
        jPanel5.add(jSeparator3);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nazwa", "Autor", "Data utworzenia" }));
        jComboBox1.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel5.add(jComboBox1);

        jSeparator1.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator1.setMaximumSize(new java.awt.Dimension(5, 32767));
        jSeparator1.setMinimumSize(new java.awt.Dimension(5, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(5, 10));
        jPanel5.add(jSeparator1);

        jPanel2.add(jPanel5);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        testsList.setModel(this.groupListModel);
        jScrollPane2.setViewportView(testsList);

        jPanel6.add(jScrollPane2);

        jPanel10.setBackground(new java.awt.Color(0, 204, 51));
        jPanel10.setForeground(new java.awt.Color(0, 204, 51));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator17.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator17.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator17.setMaximumSize(new java.awt.Dimension(10, 5));
        jSeparator17.setMinimumSize(new java.awt.Dimension(10, 5));
        jSeparator17.setPreferredSize(new java.awt.Dimension(10, 5));
        jPanel10.add(jSeparator17);

        jLabel4.setText("Sortuj");
        jPanel10.add(jLabel4);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alfabetycznie rosnąco", "Alfabetycznie malejąco" }));
        jComboBox4.setMaximumSize(new java.awt.Dimension(32767, 20));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel10.add(jComboBox4);

        jSeparator16.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator16.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator16.setMaximumSize(new java.awt.Dimension(32767, 5));
        jSeparator16.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator16.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel10.add(jSeparator16);

        jPanel6.add(jPanel10);

        jPanel2.add(jPanel6);

        jSeparator15.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator15.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator15.setMaximumSize(new java.awt.Dimension(32767, 5));
        jPanel2.add(jSeparator15);

        jTabbedPane1.addTab("Wyszukaj test", jPanel2);

        add(jTabbedPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList groupList;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JList testsList;
    // End of variables declaration//GEN-END:variables
    
    class TestCellRenderer extends JLabel implements ListCellRenderer {

        private final Color HIGHLIGHT_COLOR = new Color(0, 0, 128);

        public TestCellRenderer() {
            setOpaque(true);
        }

        @Override
        public Component getListCellRendererComponent(JList list, Object value,
                int index, boolean isSelected, boolean cellHasFocus) {
            TestDescription testDescription = (TestDescription) value;
            Formatter formatter = new Formatter();
            formatter.format("%s \t, w kategorii %s \t, dodany przez: %s \t, ocena: %d", testDescription.getName(), testDescription.getCategory(), testDescription.getAuthorLogin(), testDescription.getRating());
            setText(formatter.toString());
            if (isSelected) {
                setBackground(HIGHLIGHT_COLOR);
                setForeground(Color.white);

            } else {
                setBackground(Color.white);
                setForeground(Color.black);
            }
            return this;
        }
    }
    class GroupCellRenderer extends JLabel implements ListCellRenderer {
       
        private final Color HIGHLIGHT_COLOR = new Color(0, 0, 128);
            
        public GroupCellRenderer() {
            setOpaque(true);
        }

        @Override
        public Component getListCellRendererComponent(JList list, Object value,
                int index, boolean isSelected, boolean cellHasFocus) {
            GroupEntity groupDescription = (GroupEntity) value;
            setText(groupDescription.getName());
            if (isSelected) {
                setBackground(HIGHLIGHT_COLOR);
                setForeground(Color.white);

            } else {
                setBackground(Color.white);
                setForeground(Color.black);
            }
            return this;
        }
    }
    
}
