/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PROZE.GUI;

/**
 *
 * @author Maciek
 */
public class ViewProfile extends javax.swing.JPanel {

    /**
     * Creates new form ProfilViev
     */
    public ViewProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        Login = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        SureName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Email = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 51));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        Login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Login.setText("            Login:");
        jPanel1.add(Login);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jLabel1);

        add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 204, 51));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Name.setText("            Imie:");
        jPanel2.add(Name);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jLabel2);

        add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 204, 51));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        SureName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SureName.setText("            Nazwisko:");
        jPanel3.add(SureName);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(jLabel3);

        add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 204, 51));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        Email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Email.setText("            Email:");
        jPanel4.add(Email);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(jLabel4);

        add(jPanel4);

        jButton1.setText("Zamknij");
        add(jButton1);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel SureName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables

    public ViewProfile(String login, String name, String sureName, String email) {
        initComponents();
        jLabel1.setText(login);
        jLabel2.setText(name);
        jLabel3.setText(sureName);
        jLabel4.setText(email);
    }
}
