/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PROZE;

/**
 *
 * @author Maciek
 */
public class MyAccount extends javax.swing.JPanel {

    /**
     * Creates new form MainWindow
     */
    public MyAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        firstNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        secondNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        loginTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        emailTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        firstPasswordField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        secondPasswordField = new javax.swing.JPasswordField();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        setLayout(new java.awt.GridLayout(0, 2, 15, 15));

        jLabel7.setText("Imię:");
        add(jLabel7);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        firstNameTextField.setMaximumSize(new java.awt.Dimension(259, 25));
        firstNameTextField.setPreferredSize(new java.awt.Dimension(150, 25));
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(firstNameTextField);

        add(jPanel1);

        jLabel1.setText("Nazwisko:");
        add(jLabel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        secondNameTextField.setMaximumSize(new java.awt.Dimension(259, 25));
        secondNameTextField.setPreferredSize(new java.awt.Dimension(150, 25));
        secondNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondNameTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(secondNameTextField);

        add(jPanel2);

        jLabel2.setText("Login:");
        add(jLabel2);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        loginTextField.setMaximumSize(new java.awt.Dimension(259, 25));
        loginTextField.setPreferredSize(new java.awt.Dimension(150, 25));
        loginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(loginTextField);

        add(jPanel3);

        jLabel3.setText("Adres E-mail:");
        add(jLabel3);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        emailTextField.setMaximumSize(new java.awt.Dimension(259, 25));
        emailTextField.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel4.add(emailTextField);

        add(jPanel4);

        jLabel4.setText("Hasło:");
        add(jLabel4);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        firstPasswordField.setMaximumSize(new java.awt.Dimension(259, 25));
        firstPasswordField.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel5.add(firstPasswordField);

        add(jPanel5);

        jLabel5.setText("Powtórz hasło:");
        add(jLabel5);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        secondPasswordField.setMaximumSize(new java.awt.Dimension(259, 25));
        secondPasswordField.setPreferredSize(new java.awt.Dimension(150, 25));
        secondPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondPasswordFieldActionPerformed(evt);
            }
        });
        jPanel6.add(secondPasswordField);

        add(jPanel6);

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator8);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setText("jButton1");
        jButton1.setMaximumSize(new java.awt.Dimension(259, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(6, 20));
        jButton1.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel7.add(jButton1);

        add(jPanel7);
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void secondNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondNameTextFieldActionPerformed

    private void loginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginTextFieldActionPerformed

    private void secondPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondPasswordFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JPasswordField firstPasswordField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JTextField secondNameTextField;
    private javax.swing.JPasswordField secondPasswordField;
    // End of variables declaration//GEN-END:variables
}
