/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PROZE;

/**
 *
 * @author Krzysztof
 */
public class UserRegister extends javax.swing.JPanel {

    /**
     * Creates new form UserRegister
     */
    public UserRegister() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        nameTextField = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        secondNameTextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        loginTextField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        firstPasswordTextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        secondPasswordTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        firstMailTextField = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        secondMailTextField = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 51));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        setLayout(new java.awt.GridLayout(0, 2, 15, 0));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Imię");
        jLabel2.setDoubleBuffered(true);
        add(jLabel2);

        jSeparator1.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator1.setDoubleBuffered(true);
        add(jSeparator1);

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        nameTextField.setDoubleBuffered(true);
        nameTextField.setMaximumSize(new java.awt.Dimension(6, 20));
        nameTextField.setMinimumSize(new java.awt.Dimension(259, 25));
        nameTextField.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel1.add(nameTextField);

        add(jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName("");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        jSeparator4.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator4.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator4.setDoubleBuffered(true);
        add(jSeparator4);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Nazwisko");
        jLabel7.setDoubleBuffered(true);
        add(jLabel7);

        jSeparator5.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator5.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator5.setDoubleBuffered(true);
        add(jSeparator5);

        jPanel2.setBackground(new java.awt.Color(0, 204, 51));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        secondNameTextField.setDoubleBuffered(true);
        secondNameTextField.setMaximumSize(new java.awt.Dimension(6, 20));
        secondNameTextField.setMinimumSize(new java.awt.Dimension(259, 25));
        secondNameTextField.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel2.add(secondNameTextField);

        add(jPanel2);

        jSeparator2.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator2.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator2.setDoubleBuffered(true);
        add(jSeparator2);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Login");
        jLabel5.setDoubleBuffered(true);
        add(jLabel5);

        jSeparator6.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator6.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator6.setDoubleBuffered(true);
        add(jSeparator6);

        jPanel3.setBackground(new java.awt.Color(0, 204, 51));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        loginTextField.setDoubleBuffered(true);
        loginTextField.setMaximumSize(new java.awt.Dimension(6, 20));
        loginTextField.setMinimumSize(new java.awt.Dimension(259, 25));
        loginTextField.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel3.add(loginTextField);

        add(jPanel3);

        jSeparator3.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator3.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator3.setDoubleBuffered(true);
        add(jSeparator3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Hasło");
        jLabel4.setDoubleBuffered(true);
        add(jLabel4);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Powtórz hasło");
        jLabel6.setDoubleBuffered(true);
        add(jLabel6);

        jPanel4.setBackground(new java.awt.Color(0, 204, 51));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        firstPasswordTextField.setDoubleBuffered(true);
        firstPasswordTextField.setMaximumSize(new java.awt.Dimension(6, 20));
        firstPasswordTextField.setMinimumSize(new java.awt.Dimension(259, 25));
        firstPasswordTextField.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel4.add(firstPasswordTextField);

        add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 204, 51));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        secondPasswordTextField.setDoubleBuffered(true);
        secondPasswordTextField.setMaximumSize(new java.awt.Dimension(6, 20));
        secondPasswordTextField.setMinimumSize(new java.awt.Dimension(259, 25));
        secondPasswordTextField.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel5.add(secondPasswordTextField);

        add(jPanel5);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("E-mail");
        jLabel3.setDoubleBuffered(true);
        add(jLabel3);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Powtórz e-mail");
        jLabel8.setDoubleBuffered(true);
        add(jLabel8);

        jPanel6.setBackground(new java.awt.Color(0, 204, 51));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        firstMailTextField.setDoubleBuffered(true);
        firstMailTextField.setMaximumSize(new java.awt.Dimension(6, 20));
        firstMailTextField.setMinimumSize(new java.awt.Dimension(259, 25));
        firstMailTextField.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel6.add(firstMailTextField);

        add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(0, 204, 51));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        secondMailTextField.setDoubleBuffered(true);
        secondMailTextField.setMaximumSize(new java.awt.Dimension(6, 20));
        secondMailTextField.setMinimumSize(new java.awt.Dimension(259, 25));
        secondMailTextField.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel7.add(secondMailTextField);

        add(jPanel7);

        jSeparator7.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator7.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator7.setDoubleBuffered(true);
        add(jSeparator7);

        jSeparator8.setBackground(new java.awt.Color(0, 204, 51));
        jSeparator8.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator8.setDoubleBuffered(true);
        add(jSeparator8);

        jPanel8.setBackground(new java.awt.Color(0, 204, 51));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        okButton.setText("Zarejestruj");
        okButton.setDoubleBuffered(true);
        okButton.setMaximumSize(new java.awt.Dimension(259, 25));
        okButton.setMinimumSize(new java.awt.Dimension(6, 20));
        okButton.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel8.add(okButton);

        add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(0, 204, 51));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        cancelButton.setText("Anuluj");
        cancelButton.setDoubleBuffered(true);
        cancelButton.setMaximumSize(new java.awt.Dimension(259, 25));
        cancelButton.setMinimumSize(new java.awt.Dimension(6, 20));
        cancelButton.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel9.add(cancelButton);

        add(jPanel9);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField firstMailTextField;
    private javax.swing.JTextField firstPasswordTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField secondMailTextField;
    private javax.swing.JTextField secondNameTextField;
    private javax.swing.JTextField secondPasswordTextField;
    // End of variables declaration//GEN-END:variables
}
