/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package test;

/**
 *
 * @author Krzysztof
 */
public class UserRegister extends javax.swing.JPanel {

    /**
     * Creates new form UserRegister
     */
    public UserRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nameTextField = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        secondNameTextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        loginTextField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        firstPasswordTextField = new javax.swing.JTextField();
        secondPasswordTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        firstMailTextField = new javax.swing.JTextField();
        secondMailTextField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        setLayout(new java.awt.GridLayout(0, 2, 15, 0));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Imię");
        add(jLabel2);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator1);
        add(nameTextField);

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator4);

        jLabel7.setText("Nazwisko");
        add(jLabel7);

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator5);
        add(secondNameTextField);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator2);

        jLabel5.setText("Login");
        add(jLabel5);

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator6);
        add(loginTextField);

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jSeparator3);

        jLabel4.setText("Hasło");
        add(jLabel4);

        jLabel6.setText("Powtórz hasło");
        add(jLabel6);
        add(firstPasswordTextField);
        add(secondPasswordTextField);

        jLabel3.setText("E-mail");
        add(jLabel3);

        jLabel8.setText("Powtórz e-mail");
        add(jLabel8);
        add(firstMailTextField);
        add(secondMailTextField);

        okButton.setText("Zarejestruj");
        add(okButton);

        cancelButton.setText("Anuluj");
        add(cancelButton);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField firstMailTextField;
    private javax.swing.JTextField firstPasswordTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField secondMailTextField;
    private javax.swing.JTextField secondNameTextField;
    private javax.swing.JTextField secondPasswordTextField;
    // End of variables declaration//GEN-END:variables
}
